export const ScoreBoard = {
    ONES: 'ones',
    TWOS: 'twos',
    THREES: 'threes',
    FOURS: 'fours',
    FIVES: 'fives',
    SIXES: 'sixes',
    BONUS: 'bonus',
    ONE_PAIR: 'onePair',
    TWO_PAIRS: 'twoPairs',
    THREE_PAIRS: 'threePairs',
    THREE_ALIKE: 'threeAlike',
    FOUR_ALIKE: 'fourAlike',
    FIVE_ALIKE: 'fiveAlike',
    CABIN: 'cabin',
    HOUSE: 'house',
    TOWER: 'tower',
    SMALL_STREET: 'smallStreet',
    LARGE_STREET: 'largeStreet',
    FULL_STREET: 'fullStreet',
    CHANCE: 'chance',
    YATZY: 'yatzy',
};